### ISSUE TITLE
No rule to make target 'blackt'

### ISSUE THREAD

**Issue by grundo1561** [suppertails66/tenmatools#1]
Maybe a stupid question, but when running build.sh, it fails on the 'make blackt' step saying "No rule to make target 'blackt'.  Stop."

Should there be a Makefile in the tenma directory?

Super appreciate your work on this btw 😄

**Comment by suppertails66** [comment]
Oh. Yeah, I guess the makefile's kind of critical, isn't it? Sorry, I somehow managed to leave it out when I was putting the repo together. I've added the makefile and tested that everything actually works now. Thanks for alerting me to the issue. (Not the first time I've omitted a file by accident, but this is definitely a new low...)

I also fixed an unrelated issue where I apparently deleted one of the menu strings from the translation spreadsheet by accident at some point during development, causing the build process to break, but never realized it because the binary file that it was supposed to build to still existed on my local machine. I've fixed this and verified that I can build the translation correctly from a fresh clone of the repo, so please let me know if you run into any more issues!
